# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-29 13:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Insta_app', '0003_auto_20190729_1152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='user',
            new_name='Profile',
        ),
    ]
